CREATE database if not exists supplies;
USE supplies;

-- Tạo TABLE SDT
CREATE TABLE SDT
(
MaSDT int PRIMARY KEY  AUTO_INCREMENT,
SDT varchar(11) UNIQUE
);

-- Tạo TABLE NHACC
CREATE TABLE NHACC
(
MaNCC int PRIMARY KEY AUTO_INCREMENT,
TenNCC varchar(50) UNIQUE,
DiaChi varchar(255),
Ma_SDT int,
FOREIGN KEY(Ma_SDT) REFERENCES SDT(MaSDT)
);

-- Tạo TABLE DONDH
CREATE TABLE DONDH
(
SoDH int PRIMARY KEY AUTO_INCREMENT,
NgayDH date,
Ma_NCC int,
FOREIGN KEY(Ma_NCC) REFERENCES NHACC(MANCC)
);

-- Tạo TABLE PHIEUNHAP
CREATE TABLE PHIEUNHAP
(
SoPN int PRIMARY KEY AUTO_INCREMENT,
NgayNhap date
);

-- Tạo TABLE VATTU
CREATE TABLE VATTU
(
MaVTU int PRIMARY KEY AUTO_INCREMENT,
TenVTU varchar(50)
);

-- Tạo TABLE VATTU_PHIEUNHAP
CREATE TABLE VATTU_PHIEUNHAP
(
Ma_VTU int, So_PN int,
DGNhap int,
SLNhap int,
PRIMARY KEY(Ma_VTU, So_PN),
FOREIGN KEY(Ma_VTU) REFERENCES VATTU(MaVTU),
FOREIGN KEY(So_PN) REFERENCES PHIEUNHAP(SoPN)
);

-- Tạo TABLE PHIEUXUAT
CREATE TABLE PHIEUXUAT
(
SoPX int PRIMARY KEY AUTO_INCREMENT,
NgayXuat date
);
DROP TABLE PHIEUXUAT;

-- Tạo TABLE VATTU_PHIEUXUAT
CREATE TABLE VATTU_PHIEUXUAT 
(
Ma_VTU int, So_PX int,
DGXuat int, SLXuat int,
PRIMARY KEY(Ma_VTU, So_PX),
FOREIGN KEY(Ma_VTU) REFERENCES VATTU(MaVTU),
FOREIGN KEY(So_PX) REFERENCES PHIEUXUAT(SoPX)
);

-- Tạo TABLE VATTU_DONHANG
CREATE TABLE VATTU_DONHANG
(
Ma_VTU int, So_DH int,
PRIMARY KEY(Ma_VTU, So_DH),
FOREIGN KEY(Ma_VTU) REFERENCES VATTU(MaVTU),
FOREIGN KEY(So_DH) REFERENCES DONDH(SoDH)
);














